### ISSUE TITLE
Issue with file in YOLO step by step (forward)

### ISSUE THREAD

**Issue by Sayantan17** [jacobssy/Traffic_Sign_detection#1]
Buddy @jacobssy   hello again are you using python 3 , I will ask you doubts if I encounter any problem 1st problem - in which step you get the weights_traffic.h5 in you input? In your code
Thank you
Regards Sayantan

**Comment by jacobssy** [comment]
@Sayantan17 Hi, I use python2.7, not python3, I did not do much annotation in the file(because it is just a draft model),you could try the ipynb after modifying your data input to the correct input,and modify some config values, I wish you could run it successfully. I am doing my bachelor degree paper, after that I will continue my master degree In University Electronic Science of China about computer science, I think we could make progress each other : ) I follow you in github

**Comment by Sayantan17** [comment]
@jacobssy  i m also trying to submit a paper so I will use python 2.7  but can you tell how u got weights_traffic.h5?

**Comment by jacobssy** [comment]
@Sayantan17 you mean how to generate the weights_traffic.h5 ? or the whole process from beginning?
it is a keras api to save model.

![weights](https://user-images.githubusercontent.com/14237914/37580683-022a23d4-2b80-11e8-907e-6a1658939c4b.png)

**Comment by Sayantan17** [comment]
@jacobssy can I directly mail you if I have any problems cause putting here comments again & again is very hectic. I assume you are fine in that . Your email is that one which u provided?

**Comment by jacobssy** [comment]
@Sayantan17 yes of course :) It is my email.

**Comment by Sayantan17** [comment]
Sure Thanks a lot I will mail you when I will again try your developed code when I reach home. @jacobssy
