### ISSUE TITLE
Problem in input images

### ISSUE THREAD

**Issue by Sayantan17** [jacobssy/Traffic_Sign_detection#2]
![error](https://user-images.githubusercontent.com/37222844/37639939-5d9ec1fc-2c39-11e8-85d4-3e61598b5955.png)

 Hello @jacobssy again , Buddy can you tell how to resolve this error? The  GTSRB has 2 folders final_test & final_training & in this they have .ppm file. I assume it has error in this ;  please help me to resolve the issue.
thanking you
sayantan.

**Comment by jacobssy** [comment]
@Sayantan17 
hi,I have seen your issue, you should convert the .ppm to .jpg or change the data input type to adapt the input .
my solution is to convert the .ppm to .jpg in folder final_training ,and split the data into train_data and validation_data, the script is not so difficult(you could use the Image library to read a picture path and save it as .jpg ) :
![image](https://user-images.githubusercontent.com/14237914/37640457-a22a5c20-2c50-11e8-8bbf-e599752ab50c.png)

but this way is not the best,because you may do some slight damage to the origin picture, it is just a simple way.  you could try to change the data input type in yolo model after running model successfully

**Comment by Sayantan17** [comment]
@jacobssy how can I convert .ppm to .jpg ?

**Comment by jacobssy** [comment]
@Sayantan17 , below is a sample 
***********************************************
import Image
img = Image.open("./test.ppm")
img.save("./test.jpg")
***********************************************
so, you could use the loop to convert the whole data into the .jpg file

**Comment by Sayantan17** [comment]
I think this is available in test.ipynb ! But converting one by one is very hectic 
Shall I put folder in place of image?

**Comment by Sayantan17** [comment]
I think this is available in (test.ipynb) ! But converting one by one is very hectic 
Shall I put folder in place of image? Just by changing the directory right?
![screenshot_2018-03-20-14-15-49-471_com android chrome](https://user-images.githubusercontent.com/37222844/37644293-5637b508-2c49-11e8-8610-d1388e0843c2.png)

**Comment by jacobssy** [comment]
yes,I think you could. if I remember right ! you could try that , I spend a while to adjust the data format.

**Comment by Sayantan17** [comment]
Buddy what about validation folder how it's going to be created ? 
I will use the above steps if I face any problem I will let u Know we can sort the issue together.

**Comment by jacobssy** [comment]
I split the data in training folder into two parts: training data , validation data according to a ratio.  you could find that in ipynb. 
![image](https://user-images.githubusercontent.com/14237914/37644850-ff6124aa-2c5f-11e8-9a07-50d318c0ed53.png) 
yeah ,wish you luck.

**Comment by Sayantan17** [comment]
Thanks I will communicate with you in email from now ok?

**Comment by jacobssy** [comment]
sure , if I see that ,I will reply to you as soon as possible

**Comment by Sayantan17** [comment]
Thanks
